"""initial schema

Revision ID: 00ec4dcdd04c
Revises: 
Create Date: 2026-06-07 00:25:27.580642
"""
from alembic import op
import sqlalchemy as sa


revision = '00ec4dcdd04c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agences',
    sa.Column('id_agence', sa.Integer(), nullable=False),
    sa.Column('nom_agence', sa.String(length=100), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('code_postal', sa.String(length=10), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id_agence')
    )
    op.create_index(op.f('ix_agences_id_agence'), 'agences', ['id_agence'], unique=False)
    op.create_index(op.f('ix_agences_ville'), 'agences', ['ville'], unique=False)
    op.create_table('roles',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('nom_role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_role')
    )
    op.create_index(op.f('ix_roles_nom_role'), 'roles', ['nom_role'], unique=True)
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('date_inscription', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id_user'), 'users', ['id_user'], unique=False)
    op.create_table('employes',
    sa.Column('id_employe', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('id_agence', sa.Integer(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=32), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_agence'], ['agences.id_agence'], ),
    sa.ForeignKeyConstraint(['id_role'], ['roles.id_role'], ),
    sa.PrimaryKeyConstraint('id_employe')
    )
    op.create_index(op.f('ix_employes_email'), 'employes', ['email'], unique=True)
    op.create_index(op.f('ix_employes_id_employe'), 'employes', ['id_employe'], unique=False)
    op.create_index(op.f('ix_employes_id_role'), 'employes', ['id_role'], unique=False)
    op.create_table('messages',
    sa.Column('id_message', sa.Integer(), nullable=False),
    sa.Column('id_agence_dest', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('sujet', sa.String(length=200), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('lu', sa.Boolean(), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_agence_dest'], ['agences.id_agence'], ),
    sa.PrimaryKeyConstraint('id_message')
    )
    op.create_index(op.f('ix_messages_id_agence_dest'), 'messages', ['id_agence_dest'], unique=False)
    op.create_index(op.f('ix_messages_id_message'), 'messages', ['id_message'], unique=False)
    op.create_table('articles',
    sa.Column('id_article', sa.Integer(), nullable=False),
    sa.Column('id_auteur', sa.Integer(), nullable=True),
    sa.Column('titre', sa.String(length=300), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_auteur'], ['employes.id_employe'], ),
    sa.PrimaryKeyConstraint('id_article')
    )
    op.create_index(op.f('ix_articles_id_article'), 'articles', ['id_article'], unique=False)
    op.create_index(op.f('ix_articles_statut'), 'articles', ['statut'], unique=False)
    op.create_table('biens',
    sa.Column('id_bien', sa.Integer(), nullable=False),
    sa.Column('id_agence', sa.Integer(), nullable=False),
    sa.Column('id_commercial', sa.Integer(), nullable=True),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('adresse', sa.String(length=300), nullable=False),
    sa.Column('prix', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('surface', sa.Integer(), nullable=False),
    sa.Column('type_bien', sa.String(length=50), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('code_postal', sa.String(length=10), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('nb_pieces', sa.Integer(), nullable=False),
    sa.Column('nb_chambres', sa.Integer(), nullable=False),
    sa.Column('nb_sdb', sa.Integer(), nullable=False),
    sa.Column('caracteristiques', sa.Text(), nullable=True),
    sa.Column('terrain', sa.Boolean(), nullable=False),
    sa.Column('surface_terrain', sa.Integer(), nullable=True),
    sa.Column('mots_cles', sa.Text(), nullable=True),
    sa.Column('date_ajout', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_agence'], ['agences.id_agence'], ),
    sa.ForeignKeyConstraint(['id_commercial'], ['employes.id_employe'], ),
    sa.PrimaryKeyConstraint('id_bien')
    )
    op.create_index(op.f('ix_biens_id_agence'), 'biens', ['id_agence'], unique=False)
    op.create_index(op.f('ix_biens_id_bien'), 'biens', ['id_bien'], unique=False)
    op.create_index(op.f('ix_biens_prix'), 'biens', ['prix'], unique=False)
    op.create_index(op.f('ix_biens_statut'), 'biens', ['statut'], unique=False)
    op.create_index(op.f('ix_biens_surface'), 'biens', ['surface'], unique=False)
    op.create_index(op.f('ix_biens_type_bien'), 'biens', ['type_bien'], unique=False)
    op.create_index(op.f('ix_biens_ville'), 'biens', ['ville'], unique=False)
    op.create_table('logs',
    sa.Column('id_log', sa.Integer(), nullable=False),
    sa.Column('id_employe', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('ip_adresse', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('succes', sa.Boolean(), nullable=False),
    sa.Column('date_heure', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_employe'], ['employes.id_employe'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_index(op.f('ix_logs_action'), 'logs', ['action'], unique=False)
    op.create_index(op.f('ix_logs_date_heure'), 'logs', ['date_heure'], unique=False)
    op.create_index(op.f('ix_logs_ip_adresse'), 'logs', ['ip_adresse'], unique=False)
    op.create_table('favoris_articles',
    sa.Column('id_favori', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_article', sa.Integer(), nullable=False),
    sa.Column('date_ajout', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_article'], ['articles.id_article'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_favori'),
    sa.UniqueConstraint('id_user', 'id_article', name='uq_favori_article_user_article')
    )
    op.create_table('favoris_biens',
    sa.Column('id_favori', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_bien', sa.Integer(), nullable=False),
    sa.Column('date_ajout', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_bien'], ['biens.id_bien'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_favori'),
    sa.UniqueConstraint('id_user', 'id_bien', name='uq_favori_bien_user_bien')
    )
    op.create_table('images',
    sa.Column('id_image', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('id_bien', sa.Integer(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_bien'], ['biens.id_bien'], ),
    sa.PrimaryKeyConstraint('id_image')
    )
    op.create_index(op.f('ix_images_id_bien'), 'images', ['id_bien'], unique=False)
    op.create_table('likes',
    sa.Column('id_like', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_bien', sa.Integer(), nullable=True),
    sa.Column('id_article', sa.Integer(), nullable=True),
    sa.Column('date_ajout', sa.DateTime(), nullable=False),
    sa.CheckConstraint('id_bien IS NOT NULL OR id_article IS NOT NULL', name='ck_like_target'),
    sa.ForeignKeyConstraint(['id_article'], ['articles.id_article'], ),
    sa.ForeignKeyConstraint(['id_bien'], ['biens.id_bien'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_like'),
    sa.UniqueConstraint('id_user', 'id_article', name='uq_like_user_article'),
    sa.UniqueConstraint('id_user', 'id_bien', name='uq_like_user_bien')
    )
    op.create_table('stats_articles',
    sa.Column('id_stat', sa.Integer(), nullable=False),
    sa.Column('id_article', sa.Integer(), nullable=False),
    sa.Column('nb_vues', sa.Integer(), nullable=False),
    sa.Column('nb_likes', sa.Integer(), nullable=False),
    sa.Column('score_popularite', sa.Float(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_article'], ['articles.id_article'], ),
    sa.PrimaryKeyConstraint('id_stat'),
    sa.UniqueConstraint('id_article')
    )
    op.create_table('stats_biens',
    sa.Column('id_stat', sa.Integer(), nullable=False),
    sa.Column('id_bien', sa.Integer(), nullable=False),
    sa.Column('nb_vues', sa.Integer(), nullable=False),
    sa.Column('nb_clicks', sa.Integer(), nullable=False),
    sa.Column('nb_likes', sa.Integer(), nullable=False),
    sa.Column('score_popularite', sa.Float(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_bien'], ['biens.id_bien'], ),
    sa.PrimaryKeyConstraint('id_stat'),
    sa.UniqueConstraint('id_bien')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats_biens')
    op.drop_table('stats_articles')
    op.drop_table('likes')
    op.drop_index(op.f('ix_images_id_bien'), table_name='images')
    op.drop_table('images')
    op.drop_table('favoris_biens')
    op.drop_table('favoris_articles')
    op.drop_index(op.f('ix_logs_ip_adresse'), table_name='logs')
    op.drop_index(op.f('ix_logs_date_heure'), table_name='logs')
    op.drop_index(op.f('ix_logs_action'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_biens_ville'), table_name='biens')
    op.drop_index(op.f('ix_biens_type_bien'), table_name='biens')
    op.drop_index(op.f('ix_biens_surface'), table_name='biens')
    op.drop_index(op.f('ix_biens_statut'), table_name='biens')
    op.drop_index(op.f('ix_biens_prix'), table_name='biens')
    op.drop_index(op.f('ix_biens_id_bien'), table_name='biens')
    op.drop_index(op.f('ix_biens_id_agence'), table_name='biens')
    op.drop_table('biens')
    op.drop_index(op.f('ix_articles_statut'), table_name='articles')
    op.drop_index(op.f('ix_articles_id_article'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_messages_id_message'), table_name='messages')
    op.drop_index(op.f('ix_messages_id_agence_dest'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_employes_id_role'), table_name='employes')
    op.drop_index(op.f('ix_employes_id_employe'), table_name='employes')
    op.drop_index(op.f('ix_employes_email'), table_name='employes')
    op.drop_table('employes')
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_nom_role'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_agences_ville'), table_name='agences')
    op.drop_index(op.f('ix_agences_id_agence'), table_name='agences')
    op.drop_table('agences')
    # ### end Alembic commands ###
